language: rust
rust:
    - nightly
script:
    - cargo build --verbose
    - cargo test --all --verbose -- --nocapture

# Need to cache the whole `.cargo` directory to keep .crates.toml for
# cargo-update to work
cache:
  directories:
    - /home/travis/.cargo

# But don't cache the cargo registry
before_cache:
  - rm -rf /home/travis/.cargo/registry
