cargo-features = ["edition", "rename-dependency"]

[package]
edition = '2018'
name = "greenwasm-spectest"
version = "0.1.0"
authors = ["Marvin Löbel <loebel.marvin@gmail.com>"]

[dependencies]
wabt = "0.4.0"
