cargo-features = ["edition", "rename-dependency"]

[package]
edition = '2018'
name = "greenwasm-spectest"
version = "0.2.0"
authors = ["Marvin Löbel <loebel.marvin@gmail.com>"]

[dependencies]
wabt = { version = "0.5.0", path = "../../wabt-rs" }
