cargo-features = ["edition"]

[package]
edition = '2018'
name = "greenwasm-structure"
version = "0.1.0"
authors = ["Marvin Löbel <loebel.marvin@gmail.com>"]
license = "MIT/Apache-2.0"

readme = "README.md"

workspace = ".."

[dependencies]
